### ISSUE TITLE
OSXFUSE

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ltfs#1]
The current version is 2.8.3 not 2.7.3. I suggest in https://github.com/amiaopensource/ltfs/blob/master/BUILDING.macosx to add "or higher", as done in https://github.com/amiaopensource/ltfs/blob/master/BUILDING.linux

**Comment by dericed** [comment]
Hi Reto, I've been wondering about proceeding with this repo. The source code from various sources, HP, Quantum, IBM, Tandberg, etc all have various interoperability issues. I'm concerned that it may not be feasible or sane to try to have a central, openly-managed repo of the ltfs utilities that works for a reasonable amount of the drives. However if another archivists take on this issue I think have an ltfs repo in github that pulls in changes from the vendors could be very promising.

**Comment by retokromer** [comment]
Hello Dave: I understand. We work with a code I wrote adapting those from HP and Tandberg to our needs (as we use their tape drives in production), in a bilingual Mac OS (currently 10.10.5) and Linux (currently still Slackware 14.1 and Ubuntu 14.04 LTS) environment. At some point, I was also considering to implement the needed FUSE functionalities into Mac OS, as I am not happy with the existing, but I gave up this.

**Comment by retokromer** [comment]
P.S. - "Open LTFS" is a bigger issue, if we really wish to be open.

**Comment by retokromer** [comment]
P.P.S. - I delved a little into this and I guess it should be possible to implement an "Open LTFS" as a Brew formula during next AMIA's hackathon, if any.

**Comment by dericed** [comment]
I'm skeptical, as the vendors seem to acknowledge that the source code intentionally forks to support each vendor. Consolidating all the forks properly is a big undertaking and certainly more feasible if the LTO stakeholders and vendors were supportive.
