### ISSUE TITLE
mkltfs not working - Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by bishbashbackup** [amiaopensource/ltfs#13]
Hiya,

I've just installed this on an Ubuntu 18.04 system, which is connected to the following drives:
-Quantum LTO-6 Half-Height Drive Model B
-Quantum LTO-6 Half-Height Drive Model C

I'm able to mount tapes using the "ltfs" command. However, when I try to format a new tape, it gives me the following: 

maceadmin@amacewrk05:\~$ sudo mkltfs -d /dev/sg6
LTFS15000I Starting mkltfs, HP StoreOpen Standalone version 3.0.0, log level 2
LTFS15041I Launched by "mkltfs -d /dev/sg6"
LTFS15042I This binary is built for Linux (x86_64)
LTFS15043I GCC version is 7.5.0
LTFS17087I Kernel version: Linux version 5.4.0-70-generic (buildd@lgw01-amd64-039) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #78\~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 i386
LTFS17089I Distribution: NAME="Ubuntu"
LTFS17089I Distribution: DISTRIB_ID=Ubuntu
LTFS15003I Formatting device '/dev/sg6'
LTFS15004I LTFS volume blocksize: 524288
LTFS15005I Index partition placement policy: None

LTFS11261E Cannot load plug-in: /usr/local/lib/ltfs/libdriver-ltotape.so: undefined symbol: fuse_opt_parse
LTFS15008E Cannot open backend 'ltotape'

Seems to be a similar issue described here: https://github.com/LinearTapeFileSystem/ltfs/issues/38. Which says the following: 

> Ubuntu recently decided to enable --as-needed by default. What that flag does is to attempt to prune dependencies added to LDFLAGS but not actually used by the executable.
> 
> The thing is, we link mkltfs to libfuse, but mkltfs itself does not use any function from that library. Rather, what happens is that libtape-sg-ibmtape.so, a loadable "plugin", attempts to use a function from the FUSE library called fuse_opt_parse. Since Ubuntu's linker pruned libfuse from mkltfs, we now get an error when the plugin is loaded, since neither that plugin nor mkltfs have that symbol anymore.

If that is the case, I'm not sure the best way to work around it. Any advice would be greatly appreciated.

**Comment by bishbashbackup** [comment]
Just seen the other comments describing this repository as outdated.

So, will close the issue and look for a supported version of LTFS.

**Comment by retokromer** [comment]
@alexhabgood This LTFS implementation is six years old… Consider e.g. [that one](https://github.com/LinearTapeFileSystem/ltfs).
