### ISSUE TITLE
LTFS 3.0.0 is compatible until macOS 10.10 only

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ltfs#2]
I’m currently testing HPE StoreOpen Standalone (LTFS) 3.1.0 which works on macOS 10.11, but I don’t know yet if also on 10.12.

**Comment by dericed** [comment]
link plz

**Comment by retokromer** [comment]
The 3.0.0 installer gives an error message. I’m checking if it’s «just» FUSE or a bigger issue. – And I’m testing 3.1.0 as well.

**Comment by retokromer** [comment]
New findings:
- On page 3 of https://h20565.www2.hpe.com/hpsc/doc/public/display?sp4ts.oid=4249221&docLocale=en_US&docId=emr_na-c05206965 they say HPE StoreOpen Standalone (LTFS) 3.1.0 is supported for **macOS 10.7 through 10.11**. The link to the latest version of Compatibility Matrix on the same page is a dead one...
- Also on **Windows 10**, you better downgrade the 3.1.0 from the HP site to the 3.0.0 from the Quantum site...
- Compiling the 3.1.0 source code from HP on **Ubuntu 14.04.5 LTS** seems to work with an HP LTO drive Ultrium 6250.

**Comment by retokromer** [comment]
Useful references by SNIA (both PDF):
- [Linear Tape File System (LTFS) Format Specification. Version 2.3.0](http://www.snia.org/sites/default/files/technical_work/LTFS/LTFS_Format_2.3.0_TechPosition.pdf)
- [LTFS Bulk Transfer. Version 1.0](http://www.snia.org/sites/default/files/technical_work/LTFS/LTFS_Bulk_Transfer_1_0.pdf)

**Comment by retokromer** [comment]
Closing this, as I currently do not have the time to delve more into these internals.
