### ISSUE TITLE
scope of this repository

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ltfs#5]
Currently it contains one implementation of LTFS which is outdated. A little update has been made in https://github.com/amiaopensource/ltfs/pull/4 and https://github.com/amiaopensource/ltfs/pull/3 (i.e. the addition of another LTO-5 drive).

Should we update to one of the current LTFS implementations? Or host different implementations? Or host different versions of one implementation?

cc @dericed

**Comment by retokromer** [comment]
See also https://github.com/amiaopensource/ltopers/issues/69.

**Comment by sardaukar** [comment]
I didn't know this implementation was outdated, I thought 3.0 (with 2.2.0 format) was the latest. Where can I find a newer one?

**Comment by retokromer** [comment]
As long as I know, the officially valid standard is [ISO/IEC 20919:2016 _Information technology – Linear Tape File System (LTFS) Format Specification_](https://www.iso.org/standard/69458.html). In the real world the different implementations made by the vendors differs a little, as usual. As long as I experienced, you can switch from the one to the other, but sometimes you need to adapt the configuration. It’s not that easy as claimed by the advertising… Caveat: I did neither test all the available drives nor all the possible mixes of hardware, firmware and software.

**Comment by retokromer** [comment]
P.S.
-  ISO/IEC 20919:2016 = SNIA [Version 2.2.0](http://www.snia.org/sites/default/files/LTFS_Format_2.2.0_Technical_Position.pdf)
- SNIA latest published is [Version 2.3.0](http://www.snia.org/sites/default/files/technical_work/LTFS/LTFS_Format_2.3.0_TechPosition.pdf).
- And when reading their [Important Errata Notification for LTFS Developers](https://www.snia.org/sites/default/files/technical_work/LTFS/LTFS2.3errata.pdf), I conclude that version 2.4 should already been drafted.

cc @sardaukar

**Comment by retokromer** [comment]
Added a [log](https://github.com/amiaopensource/ltfs/blob/master/CHANGELOG.md) of the changes made to the original distribution.
