### ISSUE TITLE
Unnecessary Diagnostics dumps

### ISSUE THREAD

**Issue by scsirob** [amiaopensource/ltfs#9]
Mkltfs generates diagnostics drive dumps even when no error occurs. This is not logical and wastes time/performance. If this is by design then a flag to suppress this behaviour would be welcome. If it is unintentional then this is a bug in the code
--
LTFS15000I Starting mkltfs, LTFS version 3.0.0, log level 2
LTFS15041I Launched by "mkltfs --device=/dev/st0 -f --rules=size=2M/name=*.?mb*:*.mam:*.meta*"
LTFS15042I This binary is built for Linux (x86_64)
LTFS15043I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-28)
LTFS17087I Kernel version: Linux version 4.4.147-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Thu Aug 9 08:45:42 EDT 2018 i386
LTFS17089I Distribution: CentOS Linux release 7.5.1804 (Core)
LTFS17089I Distribution: NAME="CentOS Linux"
LTFS17089I Distribution: CentOS Linux release 7.5.1804 (Core)
LTFS17089I Distribution: CentOS Linux release 7.5.1804 (Core)
LTFS15003I Formatting device '/dev/st0'
LTFS15004I LTFS volume blocksize: 524288
LTFS15005I Index partition placement policy: size=2M/name=*.?mb*:*.mam:*.meta*

LTFS17085I Plugin: Loading "ltotape" driver
LTFS20013I Drive type is TANDBERG DATA LTO6, serial number is HU1241RR0B
LTFS17160I Maximum device block size is 524288
LTFS15049I Checking the medium (load)
LTFS15010I Creating data partition b on SCSI partition 1
LTFS15011I Creating index partition a on SCSI partition 0
LTFS17165I Resetting the medium's capacity proportion
LTFS11097I Partitioning the medium
LTFS11100I Writing label to partition b
LTFS11278I Writing index to partition b
LTFS11100I Writing label to partition a
LTFS11278I Writing index to partition a
LTFS15013I Volume UUID is: c879b889-1d2d-4c8f-9b6d-b176bbc04987

LTFS15019I Volume capacity is 2350 GB
**_LTFS20076I Triggering drive diagnostic dump
LTFS20096I Diagnostic dump complete_**
LTFS15024I Medium formatted successfully

**Comment by retokromer** [comment]
@scsirob This repository is just an outdated copy. I guess you should better send your suggestion to the original authors.
@dericed Any thoughts on this?

**Comment by scsirob** [comment]
Thank you for the reply, Reto. It was my understanding that this was the latest version. I have been testing with the IBM version ( https://github.com/LinearTapeFileSystem/ltfs ) but it does not appear to support HP drives and it has some other issues that make it hard to co-operate with my application.

**Comment by retokromer** [comment]
The different implementations of LTFS are proprietary and have indeed some incompatibilities. HPE should work fine with Tandberg, but not with IBM.

**Comment by scsirob** [comment]
Looking at the source for this 3.0.0 repository and for the 3.3.0 version on HPE's support site, the IBM version and these ones appear to have a common ancestry. The ibmtape driver sources are included but not compiled by default. Also, in this repository the IBM inquiry entries are included in the HPE ltotape driver (in tape_drivers/linux/ltotape/ltotape_supdevs.h ) but reported as DELL drives. The HPE 3.3.0 version has these removed, but I'd be surprised if adding them back wouldn't work.

**Comment by retokromer** [comment]
Indeed, it works for simple desks! I did it, but not here. For robots it’s a little more tricky, but possible as well.

**Comment by scsirob** [comment]
@retokromer I verified my initial issue (unsolicited mini-dump) with V3.3.0 and found this still to be present. It does not look like the V3.3.0 source is on Github, is this the right place to comment or should I address this elsewhere? Perhaps @dericed can comment?
--
LTFS15000I Starting mkltfs, LTFS version **_3.3.0_**, log level 2
LTFS15041I Launched by "mkltfs --device=/dev/st2 -f --rules=size=2M/name=*.?mb*:*.mam:*.meta*"
LTFS15042I This binary is built for Linux (x86_64)
LTFS15043I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-28)
LTFS17087I Kernel version: Linux version 4.4.144-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Wed Jul 25 13:54:40 EDT 2018 i386
LTFS17089I Distribution: CentOS Linux release 7.4.1708 (Core)
LTFS17089I Distribution: NAME="CentOS Linux"
LTFS17089I Distribution: CentOS Linux release 7.4.1708 (Core)
LTFS17089I Distribution: CentOS Linux release 7.4.1708 (Core)
LTFS15003I Formatting device '/dev/st2'
LTFS15004I LTFS volume blocksize: 524288
LTFS15005I Index partition placement policy: size=2M/name=*.?mb*:*.mam:*.meta*

LTFS17085I Plugin: Loading "ltotape" driver
LTFS20013I Drive type is DELL LTO6, serial number is 1202012345
LTFS17160I Maximum device block size is 524288
LTFS15049I Checking the medium (load)
LTFS15010I Creating data partition b on SCSI partition 1
LTFS15011I Creating index partition a on SCSI partition 0
LTFS17165I Resetting the medium's capacity proportion
LTFS11097I Partitioning the medium
LTFS11100I Writing label to partition b
LTFS11278I Writing index to partition b
LTFS11100I Writing label to partition a
LTFS11278I Writing index to partition a
LTFS15013I Volume UUID is: 4c48cac9-20b8-4df3-b6a2-043c2c4f10a1

LTFS15019I Volume capacity is 2440 GB
**_LTFS20076I Triggering drive diagnostic dump
LTFS20096I Diagnostic dump complete_**
LTFS15024I Medium formatted successfully

**Comment by dericed** [comment]
If the license of the 3.3 release supports it and there no significant regression, then I think a pull request here to update the repository would be welcome. As mentioned there isn't much maintenance going on here. At first I was trying to use this repository to see how the vendors branch from each other.

**Comment by scsirob** [comment]
.. Just to avoid confusion, the mini-dump worked on the DELL/IBM drive because this is not a real hardware device. It's an emulated device that accepts both IBM and HP specific SCSI commands..

**Comment by retokromer** [comment]
I would also suggest to check if the desks we have [added](https://github.com/amiaopensource/ltfs/blob/master/CHANGELOG.md) here are included in the new version.

**Comment by scsirob** [comment]
@retokromer  Those drives are the ones missing from the 3.3.0 version, it appears they were added to 3.0.0 after the initial seed so it makes sense they are missing from 3.3.0
@dericed The license is still LGPL 2.1. Having 3.3.0 on here should be OK. I'm not familiar enough with git to set up a decent pull request, especially since the files have been moved around a bit.

**Comment by retokromer** [comment]
>Those drives are the ones missing from the 3.3.0 version

Then I would suggest to add these drives to 3.3.0 as well, and to publish here the amended 3.3.0 version.

**Comment by dericed** [comment]
Going to close all issues as part of archiving this repository. Please direct issues to https://github.com/LinearTapeFileSystem/ltfs.
